### ISSUE TITLE
Create model to record attendance

### ISSUE THREAD

**Issue by ashishpahwa7** [ACE-VSIT/Library-Portal#20]
Create database design to record and retrieve attendance of members during events and meetings .

**Comment by gaurav-gogia** [comment]
I am gonna try this

**Comment by ashishpahwa7** [comment]
Assigned it to you

**Comment by ashishpahwa7** [comment]
Use the model suggested during brain storming session

**Comment by DesmondANIMUS** [comment]
Changes kr ke push kiya to tha maine
