### ISSUE TITLE
Add method for registering new user

### ISSUE THREAD

**Issue by rjvjha** [ACE-VSIT/Library-Portal#36]
Goals:
Register  a ACE/VIPS user having a unique email-id of vips.edu domain.
Register a Visitor(non VIPS)  using SocialAuth(G+ and Fb) APIs

**Comment by ashishpahwa7** [comment]
Registration alone should not grant access to access all the material unless it is approved by admin

**Comment by ashishpahwa7** [comment]
not needed now
