### ISSUE TITLE
Redirect To HomePage after log in

### ISSUE THREAD

**Issue by ashishpahwa7** [ACE-VSIT/Library-Portal#44]
Redirect to acelibraryapp/home.html after logging in

**Comment by rjvjha** [comment]
this issue is already done.

**Comment by ashishpahwa7** [comment]
@rjvjha1996  Social auth somehow managed to break it , I couldn't figure out how . Have a look at latest version of Dev

**Comment by ashishpahwa7** [comment]
It's live at : https://acelibrary.herokuapp.com/

**Comment by ashishpahwa7** [comment]
fixed
