### ISSUE TITLE
Template for Attendance

### ISSUE THREAD

**Issue by ashishpahwa7** [ACE-VSIT/Library-Portal#77]

**Comment by ashishpahwa7** [comment]
@srijitcoder  Are you working on it ?

**Comment by srijitcoder** [comment]
Yes 
check it 
latest merge ma hai.
Check UI?
I feel something is missing in that UI.
Thats why working on it

**Comment by ashishpahwa7** [comment]
Okay

**Comment by ashishpahwa7** [comment]
Don't you think we need a more descriptive view?

**Comment by srijitcoder** [comment]
Done
